//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkFTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkFTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download16 {
            get {
                object obj = ResourceManager.GetObject("download16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Instances&gt;
        ///  &lt;maxID&gt;2&lt;/maxID&gt;
        ///  &lt;Instance id=&quot;1&quot;&gt;
        ///    &lt;field type=&quot;name&quot;&gt;Piraeus SAVF&lt;/field&gt;
        ///    &lt;field type=&quot;serverAddress&quot;&gt;UNS400&lt;/field&gt;
        ///    &lt;field type=&quot;userName&quot;&gt;NIKOST&lt;/field&gt;
        ///    &lt;field type =&quot;library&quot;&gt;QGPL&lt;/field&gt;
        ///    &lt;field type=&quot;iSeriesFile&quot;&gt;IPSAVF&lt;/field&gt;
        ///    &lt;field type=&quot;windowsPath&quot;&gt;C:\SaveFiles&lt;/field&gt;
        ///    &lt;field type=&quot;windowsFile&quot;&gt;IPSAVF&lt;/field&gt;
        ///    &lt;field type=&quot;mode&quot;&gt;S&lt;/field&gt;
        ///  &lt;/Instance&gt;
        ///  &lt;Instance id=&quot;2&quot;&gt;
        ///    &lt;field type=&quot;name&quot;&gt;ING [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Instances {
            get {
                return ResourceManager.GetString("Instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selectFile16 {
            get {
                object obj = ResourceManager.GetObject("selectFile16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selectFolder16 {
            get {
                object obj = ResourceManager.GetObject("selectFolder16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ThinkFTPDatabase {
            get {
                object obj = ResourceManager.GetObject("ThinkFTPDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload16 {
            get {
                object obj = ResourceManager.GetObject("upload16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
